### ISSUE TITLE
Segmentation fault when using custom landscapes

### ISSUE THREAD

**Issue by N4th4** [Stellarium/stellarium#1179]
### Expected Behaviour
Stellarium should not crash

### Actual Behaviour
Stellarium crash (segmentation fault) as soon as you start to pan or zoom when using a custom landscape created using "Horizon" from Andrew Smith

### Steps to reproduce
1. Load custom landscape
2. Pan or zoom

### System
* Stellarium version: 0.20.2 (AppImage and from Fedora packages). Does not crash with 0.20.0 (didn't test using 0.20.1 since there is no AppImage)
* Operating system: Fedora 32
* Graphics Card: Intel Integrated

### Backtrace from gdb 
```
(gdb) bt
#0  0x00007ffff7329844 in QImage::isNull() const () from /lib64/libQt5Gui.so.5
#1  0x0000555555b41bcf in LandscapeSpherical::getOpacity(Vector3<double>) const ()
#2  0x000055555596fe26 in StelSkyDrawer::postDrawSky3dModel(StelPainter*, Vector3<float> const&, float, float, Vector3<float> const&) ()
#3  0x0000555555ab24c2 in Planet::draw3dModel(StelCore*, QSharedPointer<StelProjector::ModelViewTranform>, float, bool) ()
#4  0x0000555555ab42ac in Planet::draw(StelCore*, float, QFont const&) ()
#5  0x0000555555ac444e in SolarSystem::draw(StelCore*) ()
#6  0x00005555559901cd in StelApp::draw() ()
#7  0x00005555557e6cb7 in non-virtual thunk to StelRootItem::paint(QPainter*, QStyleOptionGraphicsItem const*, QWidget*) ()
#8  0x00007ffff7cbb2e3 in QGraphicsScenePrivate::draw(QGraphicsItem*, QPainter*, QTransform const*, QTransform const*, QRegion*, QWidget*, double, QTransform const*, bool, bool) () from /lib64/libQt5Widgets.so.5
#9  0x00007ffff7cbc310 in QGraphicsScenePrivate::drawSubtreeRecursive(QGraphicsItem*, QPainter*, QTransform const*, QRegion*, QWidget*, double, QTransform const*) () from /lib64/libQt5Widgets.so.5
#10 0x00007ffff7cbc932 in QGraphicsScenePrivate::drawItems(QPainter*, QTransform const*, QRegion*, QWidget*) () from /lib64/libQt5Widgets.so.5
#11 0x00007ffff7ce05f2 in QGraphicsView::paintEvent(QPaintEvent*) () from /lib64/libQt5Widgets.so.5
#12 0x00007ffff79d136e in QWidget::event(QEvent*) () from /lib64/libQt5Widgets.so.5
#13 0x00007ffff7a7a3b2 in QFrame::event(QEvent*) () from /lib64/libQt5Widgets.so.5
#14 0x00007ffff6a68d2e in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) () from /lib64/libQt5Core.so.5
#15 0x00007ffff7990052 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /lib64/libQt5Widgets.so.5
#16 0x00007ffff6a68fc0 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /lib64/libQt5Core.so.5
#17 0x00007ffff79c969a in QWidgetPrivate::sendPaintEvent(QRegion const&) () from /lib64/libQt5Widgets.so.5
#18 0x00007ffff79a12ee in QWidgetRepaintManager::paintAndFlush() () from /lib64/libQt5Widgets.so.5
#19 0x00007ffff79d1a97 in QWidget::event(QEvent*) () from /lib64/libQt5Widgets.so.5
#20 0x00007ffff7a7a3b2 in QFrame::event(QEvent*) () from /lib64/libQt5Widgets.so.5
#21 0x00007ffff7990063 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /lib64/libQt5Widgets.so.5
#22 0x00007ffff6a68fc0 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /lib64/libQt5Core.so.5
#23 0x00007ffff6a6bc47 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /lib64/libQt5Core.so.5
#24 0x00007ffff6ab50a7 in postEventSourceDispatch(_GSource*, int (*)(void*), void*) () from /lib64/libQt5Core.so.5
#25 0x00007ffff558278f in g_main_context_dispatch () from /lib64/libglib-2.0.so.0
#26 0x00007ffff5582b18 in g_main_context_iterate.constprop () from /lib64/libglib-2.0.so.0
#27 0x00007ffff5582be3 in g_main_context_iteration () from /lib64/libglib-2.0.so.0
#28 0x00007ffff6ab4b73 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib64/libQt5Core.so.5
#29 0x00007ffff6a6791b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib64/libQt5Core.so.5
#30 0x00007ffff6a6f5a6 in QCoreApplication::exec() () from /lib64/libQt5Core.so.5
#31 0x00005555557c2ddf in main ()
```

### Misc 
I can provide a zip with the landscape or make more tests if needed

**Comment by alex-w** [comment]
Please check latest beta

**Comment by gzotti** [comment]
This was a minor glitch which has been solved already.

**Comment by N4th4** [comment]
Tested latest beta, working without problems 👍

**Comment by alex-w** [comment]
Double of #1143
