### ISSUE TITLE
Segfault when disconnect telescope mount

### ISSUE THREAD

**Issue by vladtcvs** [Stellarium/stellarium#2090]
1. Open telescope control plugin
2. Connect to LX200-compatible telescope. It state changes from 'Stopped' to 'Connected'
3. Remove used connection serial port (/dev/ttyUSB*, /dev/pts/*, or other)

### Expected Behaviour

Telescope state changes to Stopped

### Actual Behaviour

Segfault happens

```
Thread 1 "stellarium" received signal SIGSEGV, Segmentation fault.
0x00007ffff6317d80 in main_arena () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) bt
#0  0x00007ffff6317d80 in main_arena () at /lib/x86_64-linux-gnu/libc.so.6
#1  0x00005555563397a4 in TelescopeClientDirectLx200::isConnected() const (this=0x555566d5de10)
    at /home/vlad/telescope/stellarium/plugins/TelescopeControl/src/Lx200/TelescopeClientDirectLx200.cpp:247
#2  0x00005555562f4e70 in TelescopeControl::draw(StelCore*) (this=0x555565e26690, core=0x55555718abd0)
    at /home/vlad/telescope/stellarium/plugins/TelescopeControl/src/TelescopeControl.cpp:295
#3  0x0000555555bc4845 in StelApp::draw() (this=0x555556c7b120) at /home/vlad/telescope/stellarium/src/core/StelApp.cpp:798
#4  0x0000555555940d8e in StelRootItem::paint(QPainter*, QStyleOptionGraphicsItem const*, QWidget*)
    (this=0x5555570c3640, painter=0x7fffffffd0c0, option=0x555557036598, widget=0x555557202510) at /home/vlad/telescope/stellarium/src/StelMainView.cpp:360
#5  0x00007ffff7c7332c in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#6  0x00007ffff7c741f0 in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#7  0x00007ffff7c74742 in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#8  0x00007ffff7c989f9 in QGraphicsView::paintEvent(QPaintEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#9  0x00007ffff797f2b6 in QWidget::event(QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#10 0x00007ffff7a2cd52 in QFrame::event(QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#11 0x00007ffff7c97421 in QGraphicsView::viewportEvent(QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#12 0x00007ffff68f064b in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#13 0x00007ffff793ca55 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#14 0x00007ffff79460f0 in QApplication::notify(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#15 0x00007ffff68f093a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#16 0x00007ffff7977f4a in QWidgetPrivate::sendPaintEvent(QRegion const&) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#17 0x00007ffff794e732 in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#18 0x00007ffff794f3da in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#19 0x00007ffff799d8dc in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#20 0x00007ffff799e2d0 in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#21 0x00007ffff793ca66 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#22 0x00007ffff79460f0 in QApplication::notify(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#23 0x00007ffff68f093a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#24 0x00007ffff71f5de6 in QGuiApplicationPrivate::processExposeEvent(QWindowSystemInterfacePrivate::ExposeEvent*) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#25 0x00007ffff71f6014 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#26 0x00007ffff71d035b in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#27 0x00007fffe450f32e in  () at /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#28 0x00007fffee68817d in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#29 0x00007fffee688400 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#30 0x00007fffee6884a3 in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#31 0x00007ffff6948565 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#32 0x00007ffff68ef4db in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#33 0x00007ffff68f7246 in QCoreApplication::exec() () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#34 0x0000555555917e34 in main(int, char**) (argc=1, argv=0x7fffffffe358) at /home/vlad/telescope/stellarium/src/main.cpp:390
```

### System
* Stellarium version: 5cea9c53da8f26fe313d2ccf30e8cee6583fa780
* Operating system: Ubuntu 20.04
* Graphics Card: Amd RX570
* Screen type (if applicable): 1920x1080

### Logfile 
[log.txt](https://github.com/Stellarium/stellarium/files/7676431/log.txt)

**Comment by gzotti** [comment]
@vladtcvs  How did you remove the serial port? Unplugged the cable while connection was active?

**Comment by luzpaz** [comment]
Ping @vladtcvs

**Comment by luzpaz** [comment]
No response from OP

**Comment by gzotti** [comment]
Indeed. "Report and leave" is not good here. We have occasional reports, but not the hardware to reproduce.  Scheduling for closing before 26.2.

**Comment by gzotti** [comment]
Tried with my SynScan. Disconnected cable while slewing. No crash. A simple reconnect shows the scope again.
