### ISSUE TITLE
Crash on startup (clean installation)

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#3550]
### Expected Behaviour
Create a default environment on startup of Stellarium and run planetarium

### Actual Behaviour
Crash on startup after getting location from IP address

### Steps to reproduce
1. Make a clean installation of Stellarium (or rename existing directory with settings)
2. Run Stellarium

### System
* Stellarium version: master (23.3.346)
* Operating system: macOS 11.7.10 / Ubuntu Linux 22.04.3

**Comment by 10110111** [comment]
I don't reproduce the crash.

**Comment by alex-w** [comment]
Probably the crash reproducible for Qt6-based packages only (I got crash on both machines with Qt6)

**Comment by 10110111** [comment]
I'm using Qt6 here.

**Comment by alex-w** [comment]
under gdb:
```
Got location "Barnaul, Altai Krai, Russia (53.3597, 83.758; Asia/Barnaul)" for IP "176.212.122.222"
Unable to find module called "LandscapeMgr"

Thread 1 "stellarium" received signal SIGSEGV, Segmentation fault.
0x0000555556385830 in LandscapeMgr::getFlagLandscapeAutoSelection (this=0x0) at /home/aw/devel/stellarium/src/core/modules/LandscapeMgr.cpp:1318
1318            return flagLandscapeAutoSelection;

```

**Comment by alex-w** [comment]
See `StelLocationMgr.cpp:1176` - why `LandscapeMgr` called before loading?

**Comment by alex-w** [comment]
Possible solution:
```
LandscapeMgr *lMgr=GETSTELMODULE(LandscapeMgr);
QString landscapeAutoName;
if (lMgr && lMgr->getFlagLandscapeAutoSelection())
{
	QColor color=getColorForCoordinates(loc.getLongitude(), loc.getLatitude());
	landscapeAutoName=QString("ZeroColor(%1)").arg(Vec3f(color).toStr());
}
```

But this solution will break logic for coloring the "fake landscape"

**Comment by 10110111** [comment]
> See StelLocationMgr.cpp:1176 - why LandscapeMgr called before loading?

Try `backtrace` command to see where this call comes from.

**Comment by alex-w** [comment]
```
Got location "Barnaul, Altai Krai, Russia (53.3597, 83.758; Asia/Barnaul)" for IP "176.212.122.222"
Unable to find module called "LandscapeMgr"

Thread 1 "stellarium" received signal SIGSEGV, Segmentation fault.
0x0000555556385830 in LandscapeMgr::getFlagLandscapeAutoSelection (this=0x0) at /home/aw/devel/stellarium/src/core/modules/LandscapeMgr.cpp:1318
1318            return flagLandscapeAutoSelection;
(gdb) backtrace
#0  0x0000555556385830 in LandscapeMgr::getFlagLandscapeAutoSelection() const (this=0x0) at /home/aw/devel/stellarium/src/core/modules/LandscapeMgr.cpp:1318
#1  0x00005555561ac39b in StelLocationMgr::changeLocationFromNetworkLookup() (this=0x5555583a0670)
    at /home/aw/devel/stellarium/src/core/StelLocationMgr.cpp:1176
#2  0x00005555560d42ee in StelLocationMgr::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)
    (_o=0x5555583a0670, _c=QMetaObject::InvokeMetaMethod, _id=10, _a=0x7fffffffc8a8)
    at /home/aw/devel/stellarium/builds/gcc/src/stelMain_autogen/TAC5DWH4SE/moc_StelLocationMgr.cpp:146
#3  0x00007ffff59ac273 in  () at /lib/x86_64-linux-gnu/libQt6Core.so.6
#4  0x00007ffff673d73e in  () at /lib/x86_64-linux-gnu/libQt6Network.so.6
#5  0x00007ffff59a072f in QObject::event(QEvent*) () at /lib/x86_64-linux-gnu/libQt6Core.so.6
#6  0x00007ffff6f7fd36 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt6Widgets.so.6
#7  0x00007ffff5953a58 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt6Core.so.6
#8  0x00007ffff595736a in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /lib/x86_64-linux-gnu/libQt6Core.so.6
#9  0x00007ffff5b7c637 in  () at /lib/x86_64-linux-gnu/libQt6Core.so.6
#10 0x00007ffff571bd3b in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#11 0x00007ffff5771258 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#12 0x00007ffff57193e3 in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#13 0x00007ffff5b7bf0c in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt6Core.so.6
#14 0x0000555555e407e9 in SplashScreen::showMessage(QString const&) (message=...) at /home/aw/devel/stellarium/src/StelSplashScreen.cpp:44
#15 0x0000555556208224 in StelApp::init(QSettings*) (this=0x5555582fca00, conf=0x5555585d26e0) at /home/aw/devel/stellarium/src/core/StelApp.cpp:541
#16 0x0000555555e29d7a in StelMainView::init() (this=0x7fffffffd9d0) at /home/aw/devel/stellarium/src/StelMainView.cpp:929
#17 0x0000555555e3705d in StelGLWidget::initializeGL() (this=0x5555583c6260) at /home/aw/devel/stellarium/src/StelMainView.cpp:139
#18 0x00007ffff7bdedff in QOpenGLWidget::event(QEvent*) () at /lib/x86_64-linux-gnu/libQt6OpenGLWidgets.so.6
#19 0x00007ffff6f7fd36 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt6Widgets.so.6
#20 0x00007ffff5953a58 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt6Core.so.6
#21 0x00007ffff6fd5b17 in QWidgetPrivate::show_helper() () at /lib/x86_64-linux-gnu/libQt6Widgets.so.6
#22 0x00007ffff6fd8cab in QWidgetPrivate::setVisible(bool) () at /lib/x86_64-linux-gnu/libQt6Widgets.so.6
#23 0x00007ffff6fd5a38 in QWidgetPrivate::showChildren(bool) () at /lib/x86_64-linux-gnu/libQt6Widgets.so.6
#24 0x00007ffff6fd5af3 in QWidgetPrivate::show_helper() () at /lib/x86_64-linux-gnu/libQt6Widgets.so.6
#25 0x00007ffff6fd8cab in QWidgetPrivate::setVisible(bool) () at /lib/x86_64-linux-gnu/libQt6Widgets.so.6
#26 0x00007ffff6fd57b4 in QWidget::showFullScreen() () at /lib/x86_64-linux-gnu/libQt6Widgets.so.6
#27 0x0000555555e3095e in StelMainView::setFullScreen(bool) (this=0x7fffffffd9d0, b=true) at /home/aw/devel/stellarium/src/StelMainView.cpp:1462
#28 0x0000555555dff346 in main(int, char**) (argc=1, argv=0x7fffffffdd58) at /home/aw/devel/stellarium/src/main.cpp:449

```

**Comment by gzotti** [comment]
Yes, I have run into the same problem today testing build on a super-old Core2Duo. Struggled with that with broken GPU, and now suffering from lost Geforce drivers on fresh Ubuntu 22 update. Nouveau has broken graphics on a 9600GT. Sorry, it has to do with my latest fixes around auto-landscape from GPS/network.

**Comment by gzotti** [comment]
@alex-w Something has broken a few weeks ago with the macOS CI build (errors during tool installation and "brew"ing some dependencies). And there is a deprecation warning for the Linux build as well. Can you look into these things please?

**Comment by alex-w** [comment]
> @alex-w Something has broken a few weeks ago with the macOS CI build (errors during tool installation and "brew"ing some dependencies). 

Damn... The results is weird - the unit tests looks like he depends from flags of compilers

> And there is a deprecation warning for the Linux build as well. Can you look into these things please?

Where is a deprecation warnings?

**Comment by gzotti** [comment]
![grafik](https://github.com/Stellarium/stellarium/assets/18099873/4d22465e-0d16-45b0-b6d4-efb5aa126fcb)

**Comment by alex-w** [comment]
Done. 

So, linux (x86_64; qt5/qt6), macOS 12 (x86_64; qt5/qt6) and macOS 13 (x86_64/arm64; qt6) in the box now

**Comment by alex-w** [comment]
yaml config in separate file because macOS 13 is optional for us and can be freely removed
